services:
  uw-rest-fetch:
    build: .
    command: python -m src.cli.uw_rest_fetch
    environment:
      - UNUSUAL_WHALES_API_TOKEN=${UNUSUAL_WHALES_API_TOKEN}
      - TARGET_SYMBOLS=${TARGET_SYMBOLS:-SPY,QQQ,IWM}
      - REQUEST_TIMEOUT_SECONDS=${REQUEST_TIMEOUT_SECONDS:-30.0}
      - RATE_LIMIT_REQUESTS_PER_MINUTE=${RATE_LIMIT_REQUESTS_PER_MINUTE:-100}
      - RATE_LIMIT_LEEWAY_SECONDS=${RATE_LIMIT_LEEWAY_SECONDS:-0.5}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./src:/app/src
      - ./docs:/app/docs
    tty: true
    stdin_open: true

# Usage:
#   UNUSUAL_WHALES_API_TOKEN=... docker compose run --rm uw-rest-fetch
